#!/bin/bash

if [ $# != 1 ]; then
	echo "Usage: $0 <addr>:<port>"
	exit 1
fi

ADDR=$(echo "$1" | cut -d: -f1)
PORT=$(echo "$1" | cut -d: -f2)

stty raw -echo; nc -vl -S "$ADDR" -p "$PORT"; stty -raw echo; echo -e "\rDisconnected from "$ADDR":"$PORT""
